import click
from textwrap import dedent
from typing import Any
from dotenv import load_dotenv
from litellm import completion
from litellm.exceptions import AuthenticationError


load_dotenv()  # Load environment variables from .env file


@click.group()
def cli():
    """Main command group for the AI toolbox."""
    pass


@click.command()
def hello():
    """Prints a greeting message generated by GPT-4o-mini."""
    prompt = dedent(
        """
        Generate a one-sentence, friendly and concise
        greeting message for the AI toolbox CLI user.
        """
    )
    try:
        response: Any = completion(
            model="openai/gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            stream=True,
        )
        for chunk in response:
            content = chunk.choices[0].delta.content
            if content:
                click.echo(content, nl=False)
        click.echo()
    except AuthenticationError as e:
        click.echo(
            "Authentication failed. Please check your API key."
        )
    except Exception as e:
        click.echo(f"Error generating greeting: {e}")


cli.add_command(hello)

if __name__ == "__main__":
    cli()
